export * from './LoginTemplate'
export * from './WelcomeBackTemplate'
export * from './RegisterTemplate'
export * from './SuccessfullTemplate'
export * from './ForgotPasswordTemplate'
export * from './ResetPasswordTemplate'
export * from './HomeTemplate'